apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenohttps
  namespace: kubenohttps
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: kubenohttps
          image: kubeevo.azurecr.io/kubenohttps:189
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: kubeevo-secret
